# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.0_1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.0_1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/horizon/works/RidgesFilter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/horizon/works/RidgesFilter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.0_1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.0_1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/horizon/works/RidgesFilter/CMakeFiles /Users/horizon/works/RidgesFilter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/horizon/works/RidgesFilter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ridges

# Build rule for target.
ridges: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ridges
.PHONY : ridges

# fast build rule for target.
ridges/fast:
	$(MAKE) -f CMakeFiles/ridges.dir/build.make CMakeFiles/ridges.dir/build
.PHONY : ridges/fast

src/ridges.o: src/ridges.cpp.o

.PHONY : src/ridges.o

# target to build an object file
src/ridges.cpp.o:
	$(MAKE) -f CMakeFiles/ridges.dir/build.make CMakeFiles/ridges.dir/src/ridges.cpp.o
.PHONY : src/ridges.cpp.o

src/ridges.i: src/ridges.cpp.i

.PHONY : src/ridges.i

# target to preprocess a source file
src/ridges.cpp.i:
	$(MAKE) -f CMakeFiles/ridges.dir/build.make CMakeFiles/ridges.dir/src/ridges.cpp.i
.PHONY : src/ridges.cpp.i

src/ridges.s: src/ridges.cpp.s

.PHONY : src/ridges.s

# target to generate assembly for a file
src/ridges.cpp.s:
	$(MAKE) -f CMakeFiles/ridges.dir/build.make CMakeFiles/ridges.dir/src/ridges.cpp.s
.PHONY : src/ridges.cpp.s

src/test_cpp.o: src/test_cpp.cpp.o

.PHONY : src/test_cpp.o

# target to build an object file
src/test_cpp.cpp.o:
	$(MAKE) -f CMakeFiles/ridges.dir/build.make CMakeFiles/ridges.dir/src/test_cpp.cpp.o
.PHONY : src/test_cpp.cpp.o

src/test_cpp.i: src/test_cpp.cpp.i

.PHONY : src/test_cpp.i

# target to preprocess a source file
src/test_cpp.cpp.i:
	$(MAKE) -f CMakeFiles/ridges.dir/build.make CMakeFiles/ridges.dir/src/test_cpp.cpp.i
.PHONY : src/test_cpp.cpp.i

src/test_cpp.s: src/test_cpp.cpp.s

.PHONY : src/test_cpp.s

# target to generate assembly for a file
src/test_cpp.cpp.s:
	$(MAKE) -f CMakeFiles/ridges.dir/build.make CMakeFiles/ridges.dir/src/test_cpp.cpp.s
.PHONY : src/test_cpp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ridges"
	@echo "... src/ridges.o"
	@echo "... src/ridges.i"
	@echo "... src/ridges.s"
	@echo "... src/test_cpp.o"
	@echo "... src/test_cpp.i"
	@echo "... src/test_cpp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

